export interface AiModelCatalogSyncRunRecord {
  accepted_count?: string;
  catalog_version?: string;
  change_summary?: Record<string, unknown>;
  created_at?: string;
  error_message_masked?: string;
  finished_at?: string;
  id?: string;
  legal_hold?: boolean;
  metadata?: Record<string, unknown>;
  observed_at?: string;
  observed_meter_count?: string;
  observed_model_count?: string;
  observed_price_count?: string;
  observed_vendor_count?: string;
  organization_id: string;
  payload_hash?: string;
  provider_code?: string;
  region_code?: string;
  rejected_count?: string;
  request_id?: string;
  retention_until?: string;
  run_status: string;
  skipped_count?: string;
  source_code: string;
  source_hash?: string;
  source_id?: string;
  source_type?: string;
  source_version?: string;
  started_at: string;
  status: string;
  tenant_id: string;
  trace_id?: string;
  user_id?: string;
  uuid: string;
  vendor_code?: string;
}
