export interface AiModelRecord {
  api_format?: string;
  capabilities?: Record<string, unknown>;
  capability?: string;
  capability_intro?: string;
  catalog_key: string;
  color_token?: string;
  context_tokens?: string;
  created_at?: string;
  data_scope?: string;
  default_pricing_id?: string;
  deleted_at?: string;
  deleted_by?: string;
  deprecated_at?: string;
  description?: string;
  display_name: string;
  docs_url?: string;
  family_code?: string;
  family_id?: string;
  icon_url?: string;
  id?: string;
  input_modalities?: Record<string, unknown>;
  license_type?: string;
  limitations?: Record<string, unknown>;
  max_duration_seconds?: number;
  max_input_tokens?: string;
  max_output_tokens?: string;
  metadata?: Record<string, unknown>;
  modalities?: Record<string, unknown>;
  model: string;
  model_aliases?: Record<string, unknown>;
  model_family?: string;
  model_version?: string;
  organization_id: string;
  output_modalities?: Record<string, unknown>;
  performance_profile?: Record<string, unknown>;
  provider_hint?: string;
  rank_score?: string;
  region_code: string;
  release_stage: string;
  replacement_model?: string;
  retired_at?: string;
  routing_state: string;
  shelf_state: string;
  status: string;
  supported_languages?: Record<string, unknown>;
  supports_json_schema?: boolean;
  supports_streaming?: boolean;
  supports_tools?: boolean;
  tenant_id: string;
  training_data_cutoff?: string;
  updated_at?: string;
  use_cases?: Record<string, unknown>;
  uuid: string;
  vendor_code: string;
  vendor_id?: string;
  vendor_name_snapshot?: string;
  version?: string;
}
