export interface AiQuotaPolicyRecord {
  block_duration_seconds?: string;
  burst_limit?: string;
  created_at?: string;
  data_scope?: string;
  deleted_at?: string;
  deleted_by?: string;
  effective_from?: string;
  effective_to?: string;
  exhausted_at?: string;
  group_id?: string;
  id?: string;
  metadata?: Record<string, unknown>;
  model?: string;
  name?: string;
  organization_id?: string;
  policy_code?: string;
  quota_limit?: string;
  quota_period?: string;
  quota_unit?: string;
  requests_per_day?: string;
  requests_per_minute?: string;
  requests_per_second?: string;
  reset_mode?: string;
  scope_id?: string;
  scope_type?: string;
  status?: string;
  subject_id?: string;
  subject_ref_hash?: string;
  subject_ref_masked?: string;
  subject_type?: string;
  tenant_id?: string;
  tokens_per_minute?: string;
  updated_at?: string;
  uuid?: string;
  version?: string;
}
