export interface AiRoutingDecisionLogRecord {
  api_key_id?: string;
  candidate_snapshot?: Record<string, unknown>;
  capability?: string;
  created_at?: string;
  decision_latency_ms?: number;
  decision_mode?: string;
  decision_reason?: Record<string, unknown>;
  fallback_chain?: Record<string, unknown>;
  id?: string;
  legacy_api_key_id?: string;
  legal_hold?: boolean;
  metadata?: Record<string, unknown>;
  organization_id?: string;
  payload_hash?: string;
  policy_id?: string;
  profile_id?: string;
  request_id?: string;
  requested_model?: string;
  resolved_model?: string;
  retention_until?: string;
  rule_id?: string;
  selected_account_id?: string;
  selected_channel_id?: string;
  selected_provider_id?: string;
  status?: string;
  tenant_id?: string;
  trace_id?: string;
  user_id?: string;
  uuid?: string;
}
