export interface IntegrationProviderAccountRecord {
  account_code?: string;
  account_name?: string;
  auth_config?: Record<string, unknown>;
  auth_type?: string;
  consecutive_error_count?: string;
  created_at?: string;
  credential_profile?: string;
  data_scope?: string;
  deleted_at?: string;
  deleted_by?: string;
  external_account_id?: string;
  id?: string;
  last_balance_checked_at?: string;
  last_rotated_at?: string;
  last_used_at?: string;
  last_verified_at?: string;
  masked_label?: string;
  metadata?: Record<string, unknown>;
  next_rotate_at?: string;
  organization_id?: string;
  provider_code?: string;
  provider_id?: string;
  quota_limit?: string;
  quota_unit?: string;
  quota_used?: string;
  risk_level?: string;
  secret_hash?: string;
  secret_ref?: string;
  secret_rotation_policy?: Record<string, unknown>;
  secret_version?: string;
  status?: string;
  tenant_id?: string;
  updated_at?: string;
  upstream_balance_amount?: string;
  upstream_balance_currency?: string;
  uuid?: string;
  version?: string;
}
