export interface OpsGatewayInstanceRecord {
  cell?: string;
  config_hash?: string;
  container_id_hash?: string;
  created_at?: string;
  data_scope?: string;
  deleted_at?: string;
  deleted_by?: string;
  deployment_mode?: string;
  desktop_device_hash?: string;
  health_status?: string;
  host_name?: string;
  id?: string;
  instance_code?: string;
  ip_address_hash?: string;
  ip_address_masked?: string;
  last_heartbeat_at?: string;
  metadata?: Record<string, unknown>;
  node_name?: string;
  orchestrator?: string;
  organization_id?: string;
  pod_name?: string;
  region?: string;
  runtime_type?: string;
  started_at?: string;
  status?: string;
  tenant_id?: string;
  updated_at?: string;
  uuid?: string;
  version?: string;
  version_name?: string;
}
