pub const APP_API_PREFIX: &str = "/app/v3/api";
pub const BACKEND_API_PREFIX: &str = "/backend/v3/api";

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HttpMethod {
    Delete,
    Get,
    Patch,
    Post,
    Put,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IamHttpRoute {
    pub method: HttpMethod,
    pub path: &'static str,
    pub tag: &'static str,
    pub operation_id: &'static str,
}

impl IamHttpRoute {
    pub const fn new(
        method: HttpMethod,
        path: &'static str,
        tag: &'static str,
        operation_id: &'static str,
    ) -> Self {
        Self {
            method,
            path,
            tag,
            operation_id,
        }
    }
}

pub fn app_routes() -> Vec<IamHttpRoute> {
    vec![
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/sessions",
            "auth",
            "sessions.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/auth/sessions/current",
            "auth",
            "sessions.current.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/app/v3/api/auth/sessions/current",
            "auth",
            "sessions.current.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/app/v3/api/auth/sessions/current",
            "auth",
            "sessions.current.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/sessions/refresh",
            "auth",
            "sessions.refresh",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/open_platform/qr_auth/sessions",
            "open_platform",
            "qrAuth.sessions.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/open_platform/qr_auth/sessions/{sessionKey}",
            "open_platform",
            "qrAuth.sessions.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/open_platform/qr_auth/sessions/{sessionKey}/scans",
            "open_platform",
            "qrAuth.sessions.scans.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/open_platform/qr_auth/sessions/{sessionKey}/passwords",
            "open_platform",
            "qrAuth.sessions.passwords.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/verification_codes",
            "auth",
            "verificationCodes.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/verification_codes/verify",
            "auth",
            "verificationCodes.verify",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/password_reset_requests",
            "auth",
            "passwordResetRequests.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/password_resets",
            "auth",
            "passwordResets.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/registrations",
            "auth",
            "registrations.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/auth/oauth_authorization_urls",
            "auth",
            "oauthAuthorizationUrls.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/app/v3/api/auth/oauth_sessions",
            "auth",
            "oauthSessions.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/users/current",
            "iam",
            "users.current.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/organizations",
            "iam",
            "organizations.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/organizations/tree",
            "iam",
            "organizations.tree.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/organization_memberships",
            "iam",
            "organizationMemberships.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/departments",
            "iam",
            "departments.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/departments/tree",
            "iam",
            "departments.tree.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/department_assignments",
            "iam",
            "departmentAssignments.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/positions",
            "iam",
            "positions.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/position_assignments",
            "iam",
            "positionAssignments.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/app/v3/api/iam/role_bindings",
            "iam",
            "roleBindings.list",
        ),
    ]
}

pub fn backend_routes() -> Vec<IamHttpRoute> {
    vec![
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/tenants",
            "iam",
            "tenants.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/tenants",
            "iam",
            "tenants.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/tenants/{tenantId}",
            "iam",
            "tenants.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/tenants/{tenantId}",
            "iam",
            "tenants.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/tenants/{tenantId}",
            "iam",
            "tenants.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/tenants/{tenantId}/members",
            "iam",
            "tenants.members.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/tenants/{tenantId}/members",
            "iam",
            "tenants.members.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/tenants/{tenantId}/members/{userId}",
            "iam",
            "tenants.members.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/tenants/{tenantId}/members/{userId}",
            "iam",
            "tenants.members.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/organizations",
            "iam",
            "organizations.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/organizations/{organizationId}",
            "iam",
            "organizations.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/organizations/{organizationId}",
            "iam",
            "organizations.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/organizations/{organizationId}",
            "iam",
            "organizations.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/organization_memberships",
            "iam",
            "organizationMemberships.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/organization_memberships/{membershipId}",
            "iam",
            "organizationMemberships.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/departments",
            "iam",
            "departments.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/departments/{departmentId}",
            "iam",
            "departments.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/departments/{departmentId}",
            "iam",
            "departments.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/departments/{departmentId}",
            "iam",
            "departments.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/department_assignments",
            "iam",
            "departmentAssignments.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/department_assignments/{assignmentId}",
            "iam",
            "departmentAssignments.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/positions",
            "iam",
            "positions.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/positions/{positionId}",
            "iam",
            "positions.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/positions/{positionId}",
            "iam",
            "positions.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/position_assignments",
            "iam",
            "positionAssignments.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/position_assignments/{assignmentId}",
            "iam",
            "positionAssignments.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/role_bindings",
            "iam",
            "roleBindings.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/role_bindings/{roleBindingId}",
            "iam",
            "roleBindings.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/users",
            "iam",
            "users.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/users",
            "iam",
            "users.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/users/{userId}",
            "iam",
            "users.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/users/{userId}",
            "iam",
            "users.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/users/{userId}",
            "iam",
            "users.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/roles",
            "iam",
            "roles.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/roles",
            "iam",
            "roles.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/roles/{roleId}",
            "iam",
            "roles.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/roles/{roleId}",
            "iam",
            "roles.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/roles/{roleId}",
            "iam",
            "roles.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/roles/{roleId}/permissions",
            "iam",
            "roles.permissions.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/roles/{roleId}/permissions",
            "iam",
            "roles.permissions.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/roles/{roleId}/permissions/{permissionId}",
            "iam",
            "roles.permissions.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/permissions",
            "iam",
            "permissions.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/permissions",
            "iam",
            "permissions.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/permissions/{permissionId}",
            "iam",
            "permissions.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/permissions/{permissionId}",
            "iam",
            "permissions.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/permissions/{permissionId}",
            "iam",
            "permissions.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/policies",
            "iam",
            "policies.create",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/policies",
            "iam",
            "policies.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/policies/{policyId}",
            "iam",
            "policies.retrieve",
        ),
        IamHttpRoute::new(
            HttpMethod::Patch,
            "/backend/v3/api/iam/policies/{policyId}",
            "iam",
            "policies.update",
        ),
        IamHttpRoute::new(
            HttpMethod::Delete,
            "/backend/v3/api/iam/policies/{policyId}",
            "iam",
            "policies.delete",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/api_keys",
            "iam",
            "apiKeys.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Post,
            "/backend/v3/api/iam/api_keys/{apiKeyId}/revoke",
            "iam",
            "apiKeys.revoke",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/security_events",
            "iam",
            "securityEvents.list",
        ),
        IamHttpRoute::new(
            HttpMethod::Get,
            "/backend/v3/api/iam/audit_events",
            "iam",
            "auditEvents.list",
        ),
    ]
}

pub fn required_dual_token_headers() -> [&'static str; 2] {
    ["Authorization", "Access-Token"]
}
