export interface AdminAiModelItem {
  apiFormat: string | null;
  calls: string;
  capabilityIntro: string | null;
  contextTokens: number | null;
  description: string | null;
  id: string;
  inputModalities: string[];
  limitations: string[];
  maxOutputTokens: number | null;
  modalities: string[];
  name: string;
  outputModalities: string[];
  priceIn: string;
  priceOut: string;
  releaseStage: number | null;
  replacementModel: string | null;
  routingState: number | null;
  shelfState: number | null;
  status: 'active' | 'inactive';
  supportedLanguages: string[];
  supportsJsonSchema: boolean;
  supportsStreaming: boolean;
  supportsTools: boolean;
  trainingDataCutoff: string | null;
  type: 'Chat' | 'Image' | 'Audio' | 'Embedding' | 'Music' | 'SoundEffect' | 'Video';
  useCases: string[];
  vendorCode: string;
  vendorId: string;
}
