export interface AdminSkillCreateRequest {
  builtin?: boolean;
  capabilities?: string[];
  categoryId?: string | null;
  configSchema?: Record<string, unknown>;
  coverImage?: string;
  currency?: string;
  defaultConfig?: Record<string, unknown>;
  description?: string;
  documentationUrl?: string;
  enabled?: boolean;
  entrypoint?: string;
  featured?: boolean;
  homepageUrl?: string;
  icon?: string;
  isBuiltin?: boolean;
  licenseName?: string;
  manifestUrl?: string;
  marketStatus?: 'DRAFT' | 'PUBLISHED' | 'OFFLINE' | 'DEPRECATED';
  name: string;
  packageId?: string | null;
  price?: string | null;
  provider?: string;
  recommendWeight?: number;
  repositoryUrl?: string;
  reviewStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
  runtime?: string;
  skillKey: string;
  sourceType?: 'OFFICIAL' | 'COMMUNITY' | 'ENTERPRISE' | 'PRIVATE' | 'CUSTOM';
  summary?: string;
  tags?: string[];
  version?: string;
  versionName?: string;
  visibility?: 'PUBLIC' | 'PRIVATE' | 'UNLISTED';
}
