export interface AiBillingMeterRecord {
  aggregation_mode?: string;
  allow_negative_quantity?: boolean;
  billing_mode: string;
  canonical_price_item_type?: string;
  created_at?: string;
  data_scope?: string;
  default_unit: string;
  default_unit_size: string;
  deleted_at?: string;
  deleted_by?: string;
  description?: string;
  display_name: string;
  id?: string;
  metadata?: Record<string, unknown>;
  meter_code: string;
  modality?: string;
  organization_id: string;
  quantity_precision?: number;
  quantity_source?: string;
  result_selector?: string;
  sort_order?: number;
  status: string;
  supports_expression?: boolean;
  supports_tier?: boolean;
  tenant_id: string;
  updated_at?: string;
  usage_type?: string;
  uuid: string;
  version?: string;
}
