export interface AiGenerationJobRecord {
  channel_id?: string;
  completed_at?: string;
  created_at?: string;
  failure_code?: string;
  failure_message_masked?: string;
  id?: string;
  input_asset_ids?: Record<string, unknown>;
  job_type?: string;
  legal_hold?: boolean;
  metadata?: Record<string, unknown>;
  modality?: string;
  model?: string;
  negative_prompt?: string;
  organization_id?: string;
  parameter_snapshot?: Record<string, unknown>;
  payload_hash?: string;
  progress_percent?: number;
  prompt?: string;
  provider_id?: string;
  request_id?: string;
  retention_until?: string;
  session_id?: string;
  started_at?: string;
  status?: string;
  tenant_id?: string;
  trace_id?: string;
  usage_fact_id?: string;
  user_id?: string;
  uuid?: string;
}
