export interface AiGenerationAssetRecord {
  active_index?: number;
  asset_type?: string;
  asset_url?: string;
  created_at?: string;
  data_scope?: string;
  deleted_at?: string;
  deleted_by?: string;
  download_count?: string;
  duration_seconds?: string;
  expire_at?: string;
  favorite?: boolean;
  file_size?: string;
  height?: number;
  id?: string;
  job_id?: string;
  last_accessed_at?: string;
  metadata?: Record<string, unknown>;
  mime_type?: string;
  model_snapshot?: string;
  organization_id?: string;
  owner_id?: string;
  owner_type?: string;
  parameter_snapshot?: Record<string, unknown>;
  prompt_snapshot?: string;
  share_token_hash?: string;
  shared?: boolean;
  status?: string;
  storage_key?: string;
  storage_provider?: string;
  tenant_id?: string;
  thumbnail_url?: string;
  updated_at?: string;
  user_id?: string;
  uuid?: string;
  version?: string;
  visibility?: string;
  width?: number;
}
