export interface AiModelRankSnapshotRecord {
  base_volume?: string;
  catalog_key: string;
  color_token?: string;
  context_size_text?: string;
  cost_amount?: string;
  cost_indicator?: number;
  created_at?: string;
  currency?: string;
  id?: string;
  is_new?: boolean;
  latency_p50_ms?: number;
  latency_p95_ms?: number;
  license_type?: string;
  metadata?: Record<string, unknown>;
  modality?: string;
  model: string;
  model_id?: string;
  organization_id: string;
  previous_rank_no?: number;
  pricing_text?: string;
  provider_code?: string;
  rank_no: number;
  rank_payload?: Record<string, unknown>;
  rank_scope: string;
  rebuild_version?: string;
  region_code: string;
  request_count?: string;
  snapshot_date: string;
  snapshot_period: string;
  source_id?: string;
  source_type?: string;
  source_version?: string;
  status: string;
  strengths?: Record<string, unknown>;
  success_rate?: string;
  tenant_id: string;
  token_count?: string;
  trend_score?: string;
  updated_at?: string;
  uuid: string;
  vendor_code: string;
  vendor_name_snapshot?: string;
  win_rate?: string;
}
