export interface AiPricingPlanRecord {
  base_price_side: string;
  base_pricing_scope?: string;
  billing_mode?: string;
  created_at?: string;
  currency: string;
  data_scope?: string;
  default_markup_amount?: string;
  default_multiplier?: string;
  default_reference_price_id?: string;
  deleted_at?: string;
  deleted_by?: string;
  description?: string;
  effective_from: string;
  effective_to?: string;
  fallback_mode?: string;
  id?: string;
  metadata?: Record<string, unknown>;
  min_charge_amount?: string;
  organization_id: string;
  plan_code: string;
  plan_name: string;
  plan_scope?: string;
  price_version?: string;
  priority?: number;
  rounding_mode?: string;
  status: string;
  tenant_id: string;
  updated_at?: string;
  uuid: string;
  version?: string;
}
