export interface CommerceUsageStatementRecord {
  created_at?: string;
  currency?: string;
  due_at?: string;
  export_id?: string;
  generated_at?: string;
  id?: string;
  invoice_id?: string;
  metadata?: Record<string, unknown>;
  organization_id?: string;
  owner_id?: string;
  owner_type?: string;
  paid_at?: string;
  payment_status?: string;
  period?: string;
  period_end?: string;
  period_start?: string;
  rebuild_version?: string;
  source_id?: string;
  source_type?: string;
  source_version?: string;
  statement_no?: string;
  statement_status?: string;
  status?: string;
  tenant_id?: string;
  total_cost?: string;
  total_requests?: string;
  total_tokens?: string;
  updated_at?: string;
  uuid?: string;
}
