export interface ContentSdkReleaseRecord {
  api_system?: string;
  artifact_manifest?: Record<string, unknown>;
  created_at?: string;
  data_scope?: string;
  default_base_url?: string;
  deleted_at?: string;
  deleted_by?: string;
  docs_url?: string;
  example_code?: string;
  example_manifest?: Record<string, unknown>;
  github_url?: string;
  id?: string;
  import_code?: string;
  init_code?: string;
  install_command?: string;
  language?: string;
  language_description?: string;
  language_icon?: string;
  metadata?: Record<string, unknown>;
  openapi_snapshot_id?: string;
  organization_id?: string;
  package_manager?: string;
  package_name?: string;
  published_at?: string;
  source_repo?: string;
  status?: string;
  tenant_id?: string;
  updated_at?: string;
  uuid?: string;
  version?: string;
}
