export interface IamGatewayRiskRuleRecord {
  action?: string;
  block_duration_seconds?: string;
  burst_limit?: string;
  created_at?: string;
  data_scope?: string;
  deleted_at?: string;
  deleted_by?: string;
  effective_from?: string;
  effective_to?: string;
  hit_count?: string;
  id?: string;
  last_hit_at?: string;
  match_mode?: string;
  metadata?: Record<string, unknown>;
  organization_id?: string;
  priority?: number;
  reason?: string;
  requests_per_day?: string;
  requests_per_minute?: string;
  requests_per_second?: string;
  rule_category?: string;
  rule_name?: string;
  rule_type?: string;
  scope_id?: string;
  scope_type?: string;
  status?: string;
  target_type?: string;
  target_value?: string;
  target_value_cipher_ref?: string;
  target_value_hash?: string;
  target_value_masked?: string;
  tenant_id?: string;
  tokens_per_minute?: string;
  updated_at?: string;
  uuid?: string;
  version?: string;
}
