export interface OpsCouponIssueBatchRecord {
  audience_filter?: Record<string, unknown>;
  available_count?: string;
  batch_no?: string;
  campaign_code?: string;
  claimed_count?: string;
  code_pattern?: string;
  code_prefix?: string;
  coupon_id?: string;
  coupon_template_id?: string;
  created_at?: string;
  created_by?: string;
  data_scope?: string;
  deleted_at?: string;
  deleted_by?: string;
  expire_at?: string;
  generated_at?: string;
  generated_count?: string;
  generation_status?: string;
  id?: string;
  metadata?: Record<string, unknown>;
  name?: string;
  organization_id?: string;
  requested_count?: string;
  status?: string;
  tenant_id?: string;
  updated_at?: string;
  used_count?: string;
  uuid?: string;
  version?: string;
  voided_count?: string;
}
