packages:
  - "sdks/*"
  - "packages/common/*/*"
  - "packages/native-rust/*/*"
  - "packages/pc-react/*/*"
  - "packages/mobile-react/*/*"
  - "packages/mobile-flutter/*/*"
  - "../craw-chat/sdks/sdkwork-im-sdk/sdkwork-im-sdk-typescript"
  - "../craw-chat/sdks/sdkwork-rtc-sdk/sdkwork-rtc-sdk-typescript"
  - "../craw-chat/sdks/sdkwork-rtc-sdk/sdkwork-rtc-sdk-typescript/providers/*"
  - "../sdkwork-core/sdkwork-core-pc-react"
  - "../sdkwork-ui/sdkwork-ui-pc-react"
  - "../magic-studio-v2/packages/sdkwork-app-sdk"
  - "../../sdk/sdkwork-sdk-commons/sdkwork-sdk-common-typescript"

catalog:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  lucide-react: ^1.7.0
  i18next: ^26.1.0
  qrcode: ^1.5.4
  react: ^19.2.4
  react-dom: ^19.2.4
  react-i18next: ^17.0.7
  react-hook-form: ^7.72.1
  typescript: ~6.0.2
  vite: ^8.0.3
  vite-plugin-dts: ^4.5.4
