-- Router-local messaging runtime projection until sdkwork-appbase-messaging owns bootstrap DDL.

CREATE TABLE IF NOT EXISTS messaging_provider (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    provider_code VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    channel VARCHAR(32) NOT NULL DEFAULT 'multi',
    provider_type VARCHAR(64),
    website_url VARCHAR(512),
    docs_url VARCHAR(512),
    icon_media_resource_id VARCHAR(128),
    icon_object_blob_id BIGINT,
    icon_resource_snapshot JSONB,
    metadata_schema_version VARCHAR(32),
    sort_order INTEGER
);
CREATE TABLE IF NOT EXISTS messaging_provider_account (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB,
    provider_id BIGINT,
    provider_code VARCHAR(64) NOT NULL,
    account_code VARCHAR(64) NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    delivery_purpose VARCHAR(64),
    base_url VARCHAR(512),
    auth_type VARCHAR(64),
    credential_ref VARCHAR(256),
    credential_hash VARCHAR(128),
    credential_version BIGINT,
    masked_label VARCHAR(128),
    health_status VARCHAR(32) NOT NULL DEFAULT 'unknown',
    last_verified_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS messaging_provider_capability (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    provider_code VARCHAR(64) NOT NULL,
    provider_account_id BIGINT NOT NULL DEFAULT 0,
    channel VARCHAR(32) NOT NULL,
    delivery_purpose VARCHAR(64) NOT NULL,
    country_code VARCHAR(16) NOT NULL DEFAULT '*',
    locale VARCHAR(32) NOT NULL DEFAULT '*',
    supports_template_sync BOOLEAN NOT NULL DEFAULT FALSE,
    supports_delivery_receipt BOOLEAN NOT NULL DEFAULT FALSE,
    supports_test_send BOOLEAN NOT NULL DEFAULT FALSE,
    supports_batch_send BOOLEAN NOT NULL DEFAULT FALSE,
    supports_webhook BOOLEAN NOT NULL DEFAULT FALSE,
    sandbox_supported BOOLEAN NOT NULL DEFAULT FALSE,
    capability_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
    rate_limit_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    health_status VARCHAR(32) NOT NULL DEFAULT 'unknown',
    last_verified_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS messaging_sender_identity (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    provider_account_id BIGINT NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    identity_code VARCHAR(128) NOT NULL,
    display_name VARCHAR(128),
    from_email VARCHAR(256),
    from_name VARCHAR(128),
    reply_to VARCHAR(256),
    domain_name VARCHAR(256),
    sign_name VARCHAR(128),
    sender_id VARCHAR(128),
    country_code VARCHAR(16),
    approval_status VARCHAR(32) NOT NULL DEFAULT 'draft',
    verified_at TIMESTAMPTZ,
    approval_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    rejection_reason VARCHAR(512)
);
CREATE TABLE IF NOT EXISTS messaging_template (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    template_code VARCHAR(128) NOT NULL,
    scene_code VARCHAR(128) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    delivery_purpose VARCHAR(64) NOT NULL,
    category VARCHAR(64) NOT NULL,
    owner_app_id VARCHAR(128),
    template_name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    current_version_id BIGINT,
    publish_status VARCHAR(32) NOT NULL DEFAULT 'draft'
);
CREATE TABLE IF NOT EXISTS messaging_template_version (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    template_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    subject_template VARCHAR(512),
    text_template TEXT,
    html_template TEXT,
    variable_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
    render_engine VARCHAR(32) NOT NULL DEFAULT 'handlebars',
    content_hash VARCHAR(128) NOT NULL,
    review_status VARCHAR(32) NOT NULL DEFAULT 'draft',
    published_at TIMESTAMPTZ,
    retired_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS messaging_template_variant (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    template_version_id BIGINT NOT NULL,
    channel VARCHAR(32) NOT NULL,
    locale VARCHAR(32) NOT NULL DEFAULT 'default',
    content_format VARCHAR(32) NOT NULL,
    body_template TEXT NOT NULL,
    length_limit INTEGER,
    provider_payload_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
    render_options JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS messaging_template_binding (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    template_variant_id BIGINT NOT NULL,
    provider_account_id BIGINT NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    provider_template_code VARCHAR(128) NOT NULL,
    approval_status VARCHAR(32) NOT NULL DEFAULT 'draft',
    provider_template_version VARCHAR(64),
    last_synced_at TIMESTAMPTZ,
    sync_payload_hash VARCHAR(128),
    rejection_reason VARCHAR(512),
    provider_payload JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS messaging_route_rule (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    rule_code VARCHAR(128) NOT NULL,
    app_id VARCHAR(128),
    scene_code VARCHAR(128) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    delivery_purpose VARCHAR(64) NOT NULL,
    locale VARCHAR(32) NOT NULL DEFAULT '*',
    country_code VARCHAR(16) NOT NULL DEFAULT '*',
    user_segment VARCHAR(128) NOT NULL DEFAULT '*',
    priority INTEGER NOT NULL DEFAULT 100,
    weight INTEGER NOT NULL DEFAULT 100,
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    failover_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    selection_policy JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS messaging_route_rule_target (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    route_rule_id BIGINT NOT NULL,
    provider_account_id BIGINT NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    sender_identity_id BIGINT,
    template_binding_id BIGINT,
    target_order INTEGER NOT NULL DEFAULT 1,
    weight INTEGER NOT NULL DEFAULT 100,
    circuit_breaker_policy JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS messaging_send_request (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    payload_hash VARCHAR(128) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retention_until TIMESTAMPTZ,
    legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    app_id VARCHAR(128),
    scene_code VARCHAR(128) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    delivery_purpose VARCHAR(64) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_hash VARCHAR(128) NOT NULL,
    target_masked VARCHAR(128),
    template_version_id BIGINT,
    template_variant_id BIGINT,
    resolved_route_rule_id BIGINT,
    resolved_provider_account_id BIGINT,
    resolved_sender_identity_id BIGINT,
    render_hash VARCHAR(128) NOT NULL,
    request_payload_redacted JSONB NOT NULL DEFAULT '{}'::jsonb,
    dry_run BOOLEAN NOT NULL DEFAULT FALSE,
    delivery_status VARCHAR(32) NOT NULL,
    scheduled_at TIMESTAMPTZ,
    accepted_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS messaging_send_attempt (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    payload_hash VARCHAR(128),
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retention_until TIMESTAMPTZ,
    legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    send_request_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    provider_account_id BIGINT NOT NULL,
    provider_request_id VARCHAR(256),
    provider_message_id VARCHAR(256),
    http_status INTEGER,
    provider_status VARCHAR(64),
    latency_ms INTEGER,
    failure_code VARCHAR(128),
    failure_message_masked VARCHAR(512),
    retry_after_at TIMESTAMPTZ,
    attempted_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS messaging_delivery_event (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT,
    request_id VARCHAR(128),
    trace_id VARCHAR(128),
    payload_hash VARCHAR(128) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retention_until TIMESTAMPTZ,
    legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    send_request_id BIGINT NOT NULL,
    send_attempt_id BIGINT,
    provider_code VARCHAR(64) NOT NULL,
    provider_event_id VARCHAR(256) NOT NULL,
    provider_message_id VARCHAR(256),
    event_type VARCHAR(64) NOT NULL,
    event_at TIMESTAMPTZ NOT NULL,
    payload_redacted JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS messaging_suppression (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    channel VARCHAR(32) NOT NULL,
    target_hash VARCHAR(128) NOT NULL,
    target_masked VARCHAR(128),
    reason_code VARCHAR(128) NOT NULL,
    scope_type VARCHAR(64) NOT NULL DEFAULT 'tenant',
    scope_id VARCHAR(128) NOT NULL DEFAULT '*',
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ,
    source VARCHAR(64) NOT NULL,
    note VARCHAR(512)
);
CREATE TABLE IF NOT EXISTS messaging_rate_limit_bucket (
    id BIGINT NOT NULL PRIMARY KEY,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    organization_id BIGINT NOT NULL DEFAULT 0,
    data_scope INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    scene_code VARCHAR(128) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    target_hash VARCHAR(128) NOT NULL DEFAULT '*',
    ip_hash VARCHAR(128) NOT NULL DEFAULT '*',
    device_hash VARCHAR(128) NOT NULL DEFAULT '*',
    window_start TIMESTAMPTZ NOT NULL,
    window_seconds INTEGER NOT NULL,
    send_count INTEGER NOT NULL DEFAULT 0,
    verify_count INTEGER NOT NULL DEFAULT 0,
    reject_count INTEGER NOT NULL DEFAULT 0,
    last_event_at TIMESTAMPTZ
);
